const XLSX = require('xlsx');
const { getFirestore } = require('firebase-admin/firestore');
const { getApp } = require('firebase-admin/app');

const db = () => getFirestore(getApp(), 'default');

const settingsRef = (companyId) =>
  db().collection('companies').doc(companyId).collection('settings').doc('config');

const payslipsRef = (companyId, month) =>
  db().collection('companies').doc(companyId)
      .collection('payroll').doc(month)
      .collection('payslips');

// ── RRA PAYE Declaration ──────────────────────────────────────────────────────
// Spec columns: Employee Name | National ID | Gross Salary | Transport Allowance |
//               Total Taxable Income | Tax Free (60,000) | Taxable Above Free | PAYE Amount
async function generateRRAPayeExport(companyId, month) {
  const [paysnap, settingsSnap] = await Promise.all([
    payslipsRef(companyId, month).orderBy('lastName').get(),
    settingsRef(companyId).get(),
  ]);

  const payslips = paysnap.docs.map(d => d.data());
  const settings = settingsSnap.data() || {};
  const tin = settings.rraTinNumber || '—';
  const companyName = settings.companyName || companyId;
  const monthLabel = _monthLabel(month);

  const wb = XLSX.utils.book_new();
  const ws = {};
  const colWidths = [5, 28, 18, 20, 20, 22, 20, 22, 20];
  ws['!cols'] = colWidths.map(w => ({ wch: w }));

  let row = 1;

  // ── Title block ───────────────────────────────────────────────────────────
  _setCell(ws, row++, 1, `RRA PAYE DECLARATION — ${monthLabel}`, true);
  _setCell(ws, row++, 1, companyName);
  _setCell(ws, row++, 1, `TIN: ${tin}`);
  row++; // blank row

  // ── Header ────────────────────────────────────────────────────────────────
  const headers = [
    'No.', 'Employee Name', 'National ID',
    'Gross Salary (RWF)', 'Transport Allow. (RWF)',
    'Total Taxable Income (RWF)', 'Tax Free 60,000 (RWF)',
    'Taxable Above Free (RWF)', 'PAYE Amount (RWF)',
  ];
  headers.forEach((h, c) => _setCell(ws, row, c + 1, h, true));
  row++;

  // ── Data rows ─────────────────────────────────────────────────────────────
  let totGross = 0, totTransport = 0, totTaxable = 0,
      totTaxFree = 0, totAboveFree = 0, totPaye = 0;

  payslips.forEach((ps, i) => {
    const gross     = ps.totalEarnings ?? ps.grossSalary ?? 0;
    const transport = ps.transportAllowance ?? 0;
    const taxable   = ps.adjustedGross ?? gross;
    const taxFree   = Math.min(taxable, 60000);
    const aboveFree = Math.max(0, taxable - 60000);
    const paye      = ps.paye ?? 0;

    totGross    += gross;
    totTransport += transport;
    totTaxable  += taxable;
    totTaxFree  += taxFree;
    totAboveFree += aboveFree;
    totPaye     += paye;

    const cols = [
      i + 1,
      `${ps.lastName ?? ''} ${ps.firstName ?? ''}`.trim(),
      ps.nationalId ?? '',
      _r(gross), _r(transport), _r(taxable), _r(taxFree), _r(aboveFree), _r(paye),
    ];
    cols.forEach((v, c) => _setCell(ws, row, c + 1, v));
    row++;
  });

  // ── Totals row ────────────────────────────────────────────────────────────
  const totals = ['', 'TOTAL', '', _r(totGross), _r(totTransport),
    _r(totTaxable), _r(totTaxFree), _r(totAboveFree), _r(totPaye)];
  totals.forEach((v, c) => _setCell(ws, row, c + 1, v, true));
  row += 2;

  // ── Footer / declaration ──────────────────────────────────────────────────
  _setCell(ws, row++, 1, `Company TIN: ${tin}`);
  _setCell(ws, row++, 1, `RSSB / Payroll Month: ${monthLabel}`);
  _setCell(ws, row++, 1, 'RSSB and PAYE contributions are due to RRA by the 15th of the following month.');
  _setCell(ws, row++, 1, 'I declare that all information provided above is true and correct to the best of my knowledge.');
  _setCell(ws, row++, 1, `Generated by HRNova on ${new Date().toLocaleDateString('en-GB')}`);

  ws['!ref'] = XLSX.utils.encode_range({ s: { r: 0, c: 0 }, e: { r: row, c: 8 } });
  XLSX.utils.book_append_sheet(wb, ws, 'PAYE Declaration');
  wb.Props = { Title: `RRA PAYE — ${month}`, Author: 'HRNova', CreatedDate: new Date() };

  return XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' });
}

// ── RSSB Declaration ──────────────────────────────────────────────────────────
// Spec columns: Employee Name | National ID | RSSB Number | Gross Salary | Pension Base |
//               Emp Pension 6% | Emr Pension 6% | Emp Maternity 0.3% | Emr Maternity 0.3% |
//               Emr Occ Hazard 2% | Total Employee Deductions | Total Employer Contributions
async function generateRSSBExport(companyId, month) {
  const [paysnap, settingsSnap] = await Promise.all([
    payslipsRef(companyId, month).orderBy('lastName').get(),
    settingsRef(companyId).get(),
  ]);

  const payslips = paysnap.docs.map(d => d.data());
  const settings = settingsSnap.data() || {};
  const tin = settings.rraTinNumber || '—';
  const rssbCompanyNo = settings.rssbNumber || '—';
  const companyName = settings.companyName || companyId;
  const monthLabel = _monthLabel(month);

  const wb = XLSX.utils.book_new();
  const ws = {};
  ws['!cols'] = [5, 28, 18, 16, 20, 20, 24, 24, 26, 26, 24, 26, 28].map(w => ({ wch: w }));

  let row = 1;

  // ── Title block ───────────────────────────────────────────────────────────
  _setCell(ws, row++, 1, `RSSB DECLARATION — ${monthLabel}`, true);
  _setCell(ws, row++, 1, companyName);
  _setCell(ws, row++, 1, `TIN: ${tin}   |   RSSB Employer No: ${rssbCompanyNo}`);
  row++;

  // ── Header ────────────────────────────────────────────────────────────────
  const headers = [
    'No.', 'Employee Name', 'National ID', 'RSSB Number',
    'Gross Salary (RWF)', 'Pension Base (RWF)',
    'Employee Pension 6% (RWF)', 'Employer Pension 6% (RWF)',
    'Employee Maternity 0.3% (RWF)', 'Employer Maternity 0.3% (RWF)',
    'Employer Occ. Hazard 2% (RWF)',
    'Total Employee Deductions (RWF)', 'Total Employer Contributions (RWF)',
  ];
  headers.forEach((h, c) => _setCell(ws, row, c + 1, h, true));
  row++;

  // ── Data rows ─────────────────────────────────────────────────────────────
  let t = Array(9).fill(0); // gross, penBase, pEmp, pEmr, mEmp, mEmr, occH, empTot, emrTot

  payslips.forEach((ps, i) => {
    const gross      = ps.adjustedGross ?? ps.grossSalary ?? 0; // pension base = adjustedGross
    const penBase    = gross; // same value, shown as separate column per spec
    const pEmp       = ps.pensionEmployee ?? 0;
    const pEmr       = ps.pensionEmployer ?? 0;
    const mEmp       = ps.maternityEmployee ?? 0;
    const mEmr       = ps.maternityEmployer ?? 0;
    const occH       = ps.occupationalHazard ?? 0;
    const empTotal   = pEmp + mEmp;
    const emrTotal   = pEmr + mEmr + occH;

    t[0] += gross; t[1] += penBase; t[2] += pEmp; t[3] += pEmr;
    t[4] += mEmp;  t[5] += mEmr;   t[6] += occH;
    t[7] += empTotal; t[8] += emrTotal;

    const cols = [
      i + 1,
      `${ps.lastName ?? ''} ${ps.firstName ?? ''}`.trim(),
      ps.nationalId ?? '',
      ps.rssbNumber ?? '',
      _r(gross), _r(penBase),
      _r(pEmp), _r(pEmr),
      _r(mEmp), _r(mEmr),
      _r(occH),
      _r(empTotal), _r(emrTotal),
    ];
    cols.forEach((v, c) => _setCell(ws, row, c + 1, v));
    row++;
  });

  // ── Totals row ────────────────────────────────────────────────────────────
  const totRow = ['', 'TOTAL', '', '',
    _r(t[0]), _r(t[1]), _r(t[2]), _r(t[3]),
    _r(t[4]), _r(t[5]), _r(t[6]), _r(t[7]), _r(t[8])];
  totRow.forEach((v, c) => _setCell(ws, row, c + 1, v, true));
  row += 2;

  // ── Footer / declaration ──────────────────────────────────────────────────
  _setCell(ws, row++, 1, `TIN: ${tin}   |   RSSB Employer No: ${rssbCompanyNo}`);
  _setCell(ws, row++, 1, `Payroll Month: ${monthLabel}`);
  _setCell(ws, row++, 1, 'Rates: Pension 6% employee + 6% employer | Maternity 0.3% each | Occ. Hazard 2% employer only');
  _setCell(ws, row++, 1, 'RSSB contributions are due by the 15th of the following month.');
  _setCell(ws, row++, 1, 'I declare that all information provided above is true and correct to the best of my knowledge.');
  _setCell(ws, row++, 1, `Generated by HRNova on ${new Date().toLocaleDateString('en-GB')}`);

  ws['!ref'] = XLSX.utils.encode_range({ s: { r: 0, c: 0 }, e: { r: row, c: 12 } });
  XLSX.utils.book_append_sheet(wb, ws, 'RSSB Declaration');
  wb.Props = { Title: `RSSB — ${month}`, Author: 'HRNova', CreatedDate: new Date() };

  return XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' });
}

// ── Helpers ───────────────────────────────────────────────────────────────────
function _r(v) { return Math.round(v); }

function _monthLabel(month) {
  const d = new Date(month + '-01');
  return d.toLocaleDateString('en-US', { year: 'numeric', month: 'long' });
}

function _setCell(ws, row, col, value, bold = false) {
  const addr = XLSX.utils.encode_cell({ r: row - 1, c: col - 1 });
  const type = typeof value === 'number' ? 'n' : 's';
  ws[addr] = { v: value, t: type };
  if (type === 'n') ws[addr].z = '#,##0';
  if (bold) ws[addr].s = { font: { bold: true } };
}

module.exports = { generateRRAPayeExport, generateRSSBExport };
