const XLSX = require('xlsx');
const { getFirestore } = require('firebase-admin/firestore');
const { getApp } = require('firebase-admin/app');
const { nameForCode } = require('../constants/rwandaBanks');

const db = () => getFirestore(getApp(), 'default');

const settingsRef = (companyId) =>
  db().collection('companies').doc(companyId).collection('settings').doc('config');

const payslipsRef = (companyId, month) =>
  db().collection('companies').doc(companyId)
      .collection('payroll').doc(month)
      .collection('payslips');

// ── RRA PAYE Declaration ──────────────────────────────────────────────────────
// Spec columns: Employee Name | National ID | Gross Salary | Transport Allowance |
//               Total Taxable Income | Tax Free (60,000) | Taxable Above Free | PAYE Amount
async function generateRRAPayeExport(companyId, month) {
  const [paysnap, settingsSnap] = await Promise.all([
    payslipsRef(companyId, month).orderBy('lastName').get(),
    settingsRef(companyId).get(),
  ]);

  const payslips = paysnap.docs.map(d => d.data());
  const settings = settingsSnap.data() || {};
  const tin = settings.rraTinNumber || '—';
  const companyName = settings.companyName || companyId;
  const monthLabel = _monthLabel(month);

  const wb = XLSX.utils.book_new();
  const ws = {};
  const colWidths = [5, 28, 18, 20, 20, 22, 20, 22, 20];
  ws['!cols'] = colWidths.map(w => ({ wch: w }));

  let row = 1;

  // ── Title block ───────────────────────────────────────────────────────────
  _setCell(ws, row++, 1, `RRA PAYE DECLARATION — ${monthLabel}`, true);
  _setCell(ws, row++, 1, companyName);
  _setCell(ws, row++, 1, `TIN: ${tin}`);
  row++; // blank row

  // ── Header ────────────────────────────────────────────────────────────────
  const headers = [
    'No.', 'Employee Name', 'National ID',
    'Gross Salary (RWF)', 'Transport Allow. (RWF)',
    'Total Taxable Income (RWF)', 'Tax Free 60,000 (RWF)',
    'Taxable Above Free (RWF)', 'PAYE Amount (RWF)',
  ];
  headers.forEach((h, c) => _setCell(ws, row, c + 1, h, true));
  row++;

  // ── Data rows ─────────────────────────────────────────────────────────────
  let totGross = 0, totTransport = 0, totTaxable = 0,
      totTaxFree = 0, totAboveFree = 0, totPaye = 0;

  payslips.forEach((ps, i) => {
    const gross     = ps.totalEarnings ?? ps.grossSalary ?? 0;
    const transport = ps.transportAllowance ?? 0;
    const taxable   = ps.adjustedGross ?? gross;
    const taxFree   = Math.min(taxable, 60000);
    const aboveFree = Math.max(0, taxable - 60000);
    const paye      = ps.paye ?? 0;

    totGross    += gross;
    totTransport += transport;
    totTaxable  += taxable;
    totTaxFree  += taxFree;
    totAboveFree += aboveFree;
    totPaye     += paye;

    const cols = [
      i + 1,
      `${ps.lastName ?? ''} ${ps.firstName ?? ''}`.trim(),
      ps.nationalId ?? '',
      _r(gross), _r(transport), _r(taxable), _r(taxFree), _r(aboveFree), _r(paye),
    ];
    cols.forEach((v, c) => _setCell(ws, row, c + 1, v));
    row++;
  });

  // ── Totals row ────────────────────────────────────────────────────────────
  const totals = ['', 'TOTAL', '', _r(totGross), _r(totTransport),
    _r(totTaxable), _r(totTaxFree), _r(totAboveFree), _r(totPaye)];
  totals.forEach((v, c) => _setCell(ws, row, c + 1, v, true));
  row += 2;

  // ── Footer / declaration ──────────────────────────────────────────────────
  _setCell(ws, row++, 1, `Company TIN: ${tin}`);
  _setCell(ws, row++, 1, `RSSB / Payroll Month: ${monthLabel}`);
  _setCell(ws, row++, 1, 'RSSB and PAYE contributions are due to RRA by the 15th of the following month.');
  _setCell(ws, row++, 1, 'I declare that all information provided above is true and correct to the best of my knowledge.');
  _setCell(ws, row++, 1, `Generated by HRNovva on ${new Date().toLocaleDateString('en-GB')}`);

  ws['!ref'] = XLSX.utils.encode_range({ s: { r: 0, c: 0 }, e: { r: row, c: 8 } });
  XLSX.utils.book_append_sheet(wb, ws, 'PAYE Declaration');
  wb.Props = { Title: `RRA PAYE — ${month}`, Author: 'HRNovva', CreatedDate: new Date() };

  return XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' });
}

// ── Full Payroll Export ───────────────────────────────────────────────────────
// One comprehensive sheet with everything about each employee's payroll:
// identity + bank, attendance, full earnings breakdown, every company-defined
// deduction as its own column (titles come from the payslip snapshots), PAYE,
// loans, net salary and employer contributions.
async function generatePayrollExcelExport(companyId, month) {
  const [paysnap, settingsSnap] = await Promise.all([
    payslipsRef(companyId, month).orderBy('lastName').get(),
    settingsRef(companyId).get(),
  ]);

  const payslips = paysnap.docs.map(d => d.data());
  const settings = settingsSnap.data() || {};
  const companyName = settings.companyName || companyId;
  const monthLabel = _monthLabel(month);

  // Normalize deduction lines. Payslips saved before company-defined
  // deductions existed only carry the fixed RSSB fields — map those to the
  // same {title: amount} shape so both generations export identically.
  const norm = payslips.map(ps => {
    const emp = {};
    const emr = {};
    if (Array.isArray(ps.employeeDeductions)) {
      ps.employeeDeductions.forEach(l => { emp[l.title] = (emp[l.title] || 0) + (l.amount || 0); });
    } else {
      if (ps.pensionEmployee) emp['RSSB Pension'] = ps.pensionEmployee;
      if (ps.maternityEmployee) emp['RSSB Maternity'] = ps.maternityEmployee;
    }
    if (Array.isArray(ps.employerContributions)) {
      ps.employerContributions.forEach(l => { emr[l.title] = (emr[l.title] || 0) + (l.amount || 0); });
    } else {
      if (ps.pensionEmployer) emr['RSSB Pension'] = ps.pensionEmployer;
      if (ps.maternityEmployer) emr['RSSB Maternity'] = ps.maternityEmployer;
      if (ps.occupationalHazard) emr['RSSB Occupational Hazard'] = ps.occupationalHazard;
    }
    return { ps, emp, emr };
  });

  // Union of deduction titles across all payslips → dynamic columns
  const empTitles = [...new Set(norm.flatMap(n => Object.keys(n.emp)))];
  const emrTitles = [...new Set(norm.flatMap(n => Object.keys(n.emr)))];

  const headers = [
    'No.', 'Employee Name', 'National ID', 'RSSB Number', 'Department', 'Job Title',
    'Bank', 'Account Number',
    'Working Days', 'Present Days', 'Absent Days',
    'Base Salary (RWF)', 'Transport Allow. (RWF)', 'Housing Allow. (RWF)',
    'Overtime Pay (RWF)', 'Bonuses (RWF)', 'Total Earnings (RWF)',
    'Absent Deduction (RWF)', 'Late Deduction (RWF)', 'Adjusted Gross (RWF)',
    ...empTitles.map(t => `${t} — Employee (RWF)`),
    'PAYE (RWF)', 'Loan Deductions (RWF)', 'Other Deductions (RWF)',
    'Total Deductions (RWF)', 'NET SALARY (RWF)',
    ...emrTitles.map(t => `${t} — Employer (RWF)`),
    'Total Employer Cost (RWF)',
  ];

  const wb = XLSX.utils.book_new();
  const ws = {};
  ws['!cols'] = headers.map((h, i) =>
    ({ wch: i === 1 ? 28 : Math.max(14, Math.min(30, h.length + 2)) }));

  let row = 1;

  // ── Title block ───────────────────────────────────────────────────────────
  _setCell(ws, row++, 1, `PAYROLL — ${monthLabel}`, true);
  _setCell(ws, row++, 1, companyName);
  row++;

  // ── Header ────────────────────────────────────────────────────────────────
  headers.forEach((h, c) => _setCell(ws, row, c + 1, h, true));
  row++;

  // ── Data rows ─────────────────────────────────────────────────────────────
  const totals = new Array(headers.length).fill(0);

  norm.forEach(({ ps, emp, emr }, i) => {
    const bankName = nameForCode(ps.bankCode);
    const cols = [
      i + 1,
      `${ps.lastName ?? ''} ${ps.firstName ?? ''}`.trim(),
      ps.nationalId ?? '',
      ps.rssbNumber ?? '',
      ps.department ?? '',
      ps.position ?? '',
      bankName || '—',
      ps.bankAccountNumber || '—',
      ps.workingDays ?? 0,
      ps.presentDays ?? 0,
      ps.absentDays ?? 0,
      _r(ps.baseSalary ?? 0),
      _r(ps.transportAllowance ?? 0),
      _r(ps.housingAllowance ?? 0),
      _r(ps.overtimePay ?? 0),
      _r(ps.bonuses ?? 0),
      _r(ps.totalEarnings ?? 0),
      _r(ps.absentDeduction ?? 0),
      _r(ps.lateDeduction ?? 0),
      _r(ps.adjustedGross ?? 0),
      ...empTitles.map(t => _r(emp[t] ?? 0)),
      _r(ps.paye ?? 0),
      _r(ps.loanDeductions ?? 0),
      _r(ps.extraDeductions ?? 0),
      _r(ps.totalDeductions ?? 0),
      _r(ps.netSalary ?? 0),
      ...emrTitles.map(t => _r(emr[t] ?? 0)),
      _r(ps.totalEmployerCost ?? 0),
    ];
    cols.forEach((v, c) => {
      _setCell(ws, row, c + 1, v);
      if (typeof v === 'number' && c >= 8) totals[c] += v;
    });
    row++;
  });

  // ── Totals row (numeric columns only) ─────────────────────────────────────
  const totalRow = headers.map((h, c) => {
    if (c === 1) return 'TOTAL';
    return c >= 8 ? _r(totals[c]) : '';
  });
  totalRow.forEach((v, c) => _setCell(ws, row, c + 1, v, true));
  row += 2;

  // ── Footer ────────────────────────────────────────────────────────────────
  _setCell(ws, row++, 1, `Total employees: ${payslips.length}`);
  _setCell(ws, row++, 1, 'Statutory contributions and PAYE are due to RRA by the 15th of the following month.');
  _setCell(ws, row++, 1, `Generated by HRNovva on ${new Date().toLocaleDateString('en-GB')}`);

  ws['!ref'] = XLSX.utils.encode_range({ s: { r: 0, c: 0 }, e: { r: row, c: headers.length - 1 } });
  XLSX.utils.book_append_sheet(wb, ws, 'Payroll');
  wb.Props = { Title: `Payroll — ${month}`, Author: 'HRNovva', CreatedDate: new Date() };

  return XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' });
}

// ── Helpers ───────────────────────────────────────────────────────────────────
function _r(v) { return Math.round(v); }

function _monthLabel(month) {
  const d = new Date(month + '-01');
  return d.toLocaleDateString('en-US', { year: 'numeric', month: 'long' });
}

function _setCell(ws, row, col, value, bold = false) {
  const addr = XLSX.utils.encode_cell({ r: row - 1, c: col - 1 });
  const type = typeof value === 'number' ? 'n' : 's';
  ws[addr] = { v: value, t: type };
  if (type === 'n') ws[addr].z = '#,##0';
  if (bold) ws[addr].s = { font: { bold: true } };
}

module.exports = { generateRRAPayeExport, generatePayrollExcelExport };
