name: hrnova
description: "HRNovva — Your HR Team, Supercharged"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.9
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.0.1
  camera: ^0.11.1
  image_picker: ^1.1.2
  image: ^4.3.0
  dio: ^5.8.0
  pdf: ^3.11.3
  printing: ^5.14.2
  fl_chart: ^0.70.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^18.0.1
  flutter_markdown: ^0.7.7
  heroicons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/icon.png
    - assets/icon/icon_light.png
    - assets/icon/icon_dark.png
  fonts:
    - family: General Sans
      fonts:
        - asset: assets/fonts/GeneralSans/GeneralSans-Light.ttf
          weight: 300
        - asset: assets/fonts/GeneralSans/GeneralSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/GeneralSans/GeneralSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/GeneralSans/GeneralSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GeneralSans/GeneralSans-Semibold.ttf
          weight: 600
        - asset: assets/fonts/GeneralSans/GeneralSans-Bold.ttf
          weight: 700
